schema_version: 1

context:
  name: casregnum
  version: 1.1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/casregnum-${{ version }}.tar.gz
  sha256: bd49dd0843321d001ecda658613c368b6a7a553ea6b3078c89eff5d738936d61

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - casregnum
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: casregnum provides a Python class 'CAS' for working with CAS Registry Numbers®. It allows managing, sorting and checking CAS numbers.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/molshape/CASRegistryNumbers

extra:
  recipe-maintainers:
    - HLinde
